# coding: latin-1
###############################################################################
# Copyright (c) 2026 European Commission
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
###############################################################################

# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-02-09T17:28:23+00:00
# datamodel-codegen --input app/json_gen/schema.json --output models.py --output-model-type dataclasses.dataclass 

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing_extensions import Any, TypeAlias

LoTEVersionIdentifier: TypeAlias = int


LoTESequenceNumber: TypeAlias = int


LoTEType: TypeAlias = str


@dataclass
class MultiLangString:
    lang: str
    value: str


@dataclass
class NonEmptyMultiLangURI:
    lang: str
    uriValue: str


SchemeOperatorName: TypeAlias = list[MultiLangString]


@dataclass
class PostalAddress:
    lang: str
    StreetAddress: str
    Country: str
    Locality: str | None = None
    StateOrProvince: str | None = None
    PostalCode: str | None = None


ElectronicAddress: TypeAlias = list[NonEmptyMultiLangURI]


SchemeName: TypeAlias = list[MultiLangString]


SchemeInformationURI: TypeAlias = list[NonEmptyMultiLangURI]


StatusDeterminationApproach: TypeAlias = str


SchemeTypeCommunityRules: TypeAlias = list[NonEmptyMultiLangURI]


SchemeTerritory: TypeAlias = str


PolicyOrLegalNotice: TypeAlias = list[Any]


HistoricalInformationPeriod: TypeAlias = int


@dataclass
class PkiOb:
    val: str
    encoding: str | None = None
    specRef: str | None = None


X509SubjectName: TypeAlias = str


class Kty(Enum):
    EC = 'EC'
    RSA = 'RSA'
    oct = 'oct'


class Use(Enum):
    sig = 'sig'
    enc = 'enc'


class KeyOps(Enum):
    sign = 'sign'
    verify = 'verify'
    encrypt = 'encrypt'
    decrypt = 'decrypt'
    wrapKey = 'wrapKey'
    unwrapKey = 'unwrapKey'
    deriveKey = 'deriveKey'
    deriveBits = 'deriveBits'


@dataclass
class Jwk:
    kty: Kty
    use: Use | None = None
    key_ops: KeyOps | None = None
    alg: str | None = None
    kid: str | None = None
    x5u: str | None = None
    x5c: list[str] | None = None
    x5t: str | None = None
    x5t_S256: str | None = None


X509SKI: TypeAlias = str


OtherId: TypeAlias = str


MimeType: TypeAlias = str


ListIssueDateTime: TypeAlias = str


NextUpdate: TypeAlias = str


DistributionPoints: TypeAlias = list[str]


SchemeExtensions: TypeAlias = list[Any]


ServiceTypeIdentifier: TypeAlias = str


ServiceName: TypeAlias = list[MultiLangString]


ServiceStatus: TypeAlias = str


StatusStartingTime: TypeAlias = str


SchemeServiceDefinitionURI: TypeAlias = list[NonEmptyMultiLangURI]


@dataclass
class ServiceSupplyPointURI:
    uriValue: str
    ServiceType: str | None = None


ServiceDefinitionURI: TypeAlias = list[NonEmptyMultiLangURI]


ServiceInformationExtensions: TypeAlias = list[Any]


TEName: TypeAlias = list[MultiLangString]


TETradeName: TypeAlias = list[MultiLangString]


TEInformationURI: TypeAlias = list[NonEmptyMultiLangURI]


TEInformationExtensions: TypeAlias = list[Any]


PostalAddresses: TypeAlias = list[PostalAddress]


PublicKeyValue: TypeAlias = Jwk


@dataclass
class LoTEQualifier:
    LoTEType: LoTEType
    SchemeOperatorName: SchemeOperatorName
    MimeType: MimeType
    SchemeTypeCommunityRules: SchemeTypeCommunityRules | None = None
    SchemeTerritory: SchemeTerritory | None = None


ServiceSupplyPoints: TypeAlias = list[ServiceSupplyPointURI]


@dataclass
class TEAddress:
    TEPostalAddress: PostalAddresses
    TEElectronicAddress: ElectronicAddress


@dataclass
class SchemeOperatorAddress:
    SchemeOperatorPostalAddress: PostalAddresses
    SchemeOperatorElectronicAddress: ElectronicAddress


@dataclass
class ServiceDigitalIdentity:
    X509Certificates: list[PkiOb] | None = None
    X509SubjectNames: list[X509SubjectName] | None = None
    PublicKeyValues: list[PublicKeyValue] | None = None
    X509SKIs: list[X509SKI] | None = None
    OtherIds: list[OtherId] | None = None
    additionalProperties: Any | None = None


@dataclass
class ServiceInformation:
    ServiceName: ServiceName
    ServiceDigitalIdentity: ServiceDigitalIdentity
    ServiceTypeIdentifier: ServiceTypeIdentifier | None = None
    ServiceStatus: ServiceStatus | None = None
    StatusStartingTime: StatusStartingTime | None = None
    SchemeServiceDefinitionURI: SchemeServiceDefinitionURI | None = None
    ServiceSupplyPoints: ServiceSupplyPoints | None = None
    ServiceDefinitionURI: ServiceDefinitionURI | None = None
    ServiceInformationExtensions: ServiceInformationExtensions | None = None


@dataclass
class ServiceHistoryInstance:
    ServiceName: ServiceName
    ServiceDigitalIdentity: ServiceDigitalIdentity
    ServiceStatus: ServiceStatus
    StatusStartingTime: StatusStartingTime
    ServiceTypeIdentifier: ServiceTypeIdentifier | None = None
    ServiceInformationExtensions: ServiceInformationExtensions | None = None


@dataclass
class TrustedEntityInformation:
    TEName: TEName
    TEAddress: TEAddress
    TEInformationURI: TEInformationURI
    TETradeName: TETradeName | None = None
    TEInformationExtensions: TEInformationExtensions | None = None


@dataclass
class OtherLoTEPointer:
    LoTELocation: str
    ServiceDigitalIdentities: list[ServiceDigitalIdentity]
    LoTEQualifiers: list[LoTEQualifier]


ServiceHistory: TypeAlias = list[ServiceHistoryInstance]


PointersToOtherLoTE: TypeAlias = list[OtherLoTEPointer]


@dataclass
class TrustedEntityService:
    ServiceInformation: ServiceInformation
    ServiceHistory: ServiceHistory | None = None


@dataclass
class ListAndSchemeInformation:
    LoTEVersionIdentifier: LoTEVersionIdentifier
    LoTESequenceNumber: LoTESequenceNumber
    SchemeOperatorName: SchemeOperatorName
    ListIssueDateTime: ListIssueDateTime
    NextUpdate: NextUpdate
    LoTEType: LoTEType | None = None
    SchemeOperatorAddress: SchemeOperatorAddress | None = None
    SchemeName: SchemeName | None = None
    SchemeInformationURI: SchemeInformationURI | None = None
    StatusDeterminationApproach: StatusDeterminationApproach | None = None
    SchemeTypeCommunityRules: SchemeTypeCommunityRules | None = None
    SchemeTerritory: SchemeTerritory | None = None
    PolicyOrLegalNotice: PolicyOrLegalNotice | None = None
    HistoricalInformationPeriod: HistoricalInformationPeriod | None = None
    PointersToOtherLoTE: PointersToOtherLoTE | None = None
    DistributionPoints: DistributionPoints | None = None
    SchemeExtensions: SchemeExtensions | None = None


TrustedEntityServices: TypeAlias = list[TrustedEntityService]


@dataclass
class TrustedEntity:
    TrustedEntityInformation: TrustedEntityInformation
    TrustedEntityServices: TrustedEntityServices


TrustedEntitiesList: TypeAlias = list[TrustedEntity]


@dataclass
class LoTE:
    ListAndSchemeInformation: ListAndSchemeInformation
    TrustedEntitiesList: TrustedEntitiesList | None = None


@dataclass
class Model:
    LoTE: LoTE
