services:
  tsl_manager:
    image: ghcr.io/niscy-eudiw/eudi-srv-web-trustedlist-manager-py:latest
    container_name: tsl_manager
    ports:
      - "5000:5000"
    environment:
      FLASK_RUN_PORT: 5000
      SERVICE_URL: "http://127.0.0.1:5000/"
      #Container path, validate vp token
      TRUSTED_CAS_PATH: "/app/certs/CAs"
      VERIFIER: "verifier-backend.eudiw.dev"
      SCA_SIGNER_URL: "http://localhost:8086"
      LOG_PATH: "/app/logs"
      DB_HOST: "host.docker.internal"
      DB_PORT: 
      DB_USER: 
      DB_PASSWORD: 
      DB_NAME: "trusted_lists"
      #dictionary containing certificate and privake key locations for signing TSL and LoTEs
      #Example
      #{
      # "UT":["app/certs/certs_and_privkeys/ecdsa_cert.pem", "app/certs/certs_and_privkeys/ecdsa_key.pem"]
      # }
      CERT_AND_PRIVKEY_LOCATIONS: 

    # local path : container path
    volumes:
      - ./CAs: /app/certs/CAs
      - ./certs_and_privkeys: /app/certs/certs_and_privkeys





